// import "./Any-Champs-Swarm/index.js"
// import "./Auto-Hide-Swarm-Completed-Missions/index.js"
// import "./Auto-Message/index"
// import "./Bad-Apple-Status/index.js"
// import "./Force-Jungle-Lane/Force_Jungle-Lane.js"
// import "./Get-Mastery-Score/index.js"
// import "./Hide-Friends-List/index.js"
// import "./Invite-All-Friends/index.js"
// import "./Recruit a LoL/index.js"